#! /usr/bin/env bash

VAGRANT_CONFIG=`cat << EOT
{
  "guest_ip": "192.168.33.100",
  "chef_target": "docker",
  "hosts": [
  ],
  "exports": {
  },
  "fstab": [
  ]
}
EOT`

SERVER_NAMES=''

if [ ! -d server ] ; then
  git submodule init
  git submodule update
fi

source ./server/vagrant-prepare.sh

